version: "3.9"
services:
  app:
    image: localhost:5000/moi-java
    networks:
      - backend-nw
    environment:
      - MYSQL_JDBC_URL=${MYSQL_JDBC_URL}
      - MYSQL_JDBC_USER=${MYSQL_JDBC_USER}
      - MYSQL_JDBC_PASSWORD=${MYSQL_JDBC_PASSWORD}
    ports:
      - "8007:8080"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  backend-nw:
    external: true