version: "3.9"
services:
  app:
    image: localhost:5000/moi-java
    networks:
      - backend-nw
    ports:
      - "8007:8080"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  backend-nw:
    external: true