version: '3.7'

services:
  mysqldb:
    image: mysql:latest
    #    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moi
      MYSQL_USER: santa
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
#    volumes:
#      - ./mysql-data:/var/lib/mysql