---
version: "3.7"
services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: buimonDb
      MYSQL_USER: santander
      MYSQL_PASSWORD: santa16
    ports:
      - 3307:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
