CREATE TABLE product (
idProduct BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL ,
color VARCHAR(50) NULL DEFAULT NULL,
imei bigint NULL DEFAULT NULL,
code VARCHAR(50) NULL DEFAULT NULL,
coming DATE NULL DEFAULT NULL,
type VARCHAR(60) NULL DEFAULT NULL
);